Check for ar

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -60,6 +60,17 @@ done
 cd - > /dev/null 2>&1
 rm -rf /tmp/e10b5eccac1ecb4e8706e3898719b197a1e9d10d65e860192d38155cb31233ea-configure
 
+# Check for ar
+printf "Checking for ar..."
+if command -v ar &> /dev/null
+then
+    echo "found"
+else
+    echo "not found"
+    echo "ar not found. Please install it to continue."
+    exit 1
+fi
+
 # Check OS type in order to determine proper sed
 # Detect OS and set sed -i syntax
 if [[ "$OSTYPE" == "darwin"* ]]; then
