Just remove the gui from the UNIX build system altogether

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -120,60 +120,60 @@ else
 fi
 
 # Check whether to build GUI
-printf "Checking if GUI should be built..."
-if printf '%s\n' "$@" | grep -q -- "^--enable-gui$"; then
-    echo "yes"
-    BUILD_GUI="TRUE"
-else
-    echo "no"
-    BUILD_GUI="FALSE"
-fi
+# printf "Checking if GUI should be built..."
+# if printf '%s\n' "$@" | grep -q -- "^--enable-gui$"; then
+#     echo "yes"
+#     BUILD_GUI="TRUE"
+# else
+#     echo "no"
+#     BUILD_GUI="FALSE"
+# fi
 
 # Check for python
-if [ "$BUILD_GUI" = "TRUE" ]; then
-    printf "Checking for python..."
-    if command -v python &> /dev/null || command -v python3 &> /dev/null
-    then
-        echo "found"
-    else
-        echo "not found"
-        echo "python not found. Please install it to continue."
-        exit 1
-    fi
+# if [ "$BUILD_GUI" = "TRUE" ]; then
+#     printf "Checking for python..."
+#     if command -v python &> /dev/null || command -v python3 &> /dev/null
+#     then
+#         echo "found"
+#     else
+#         echo "not found"
+#         echo "python not found. Please install it to continue."
+#         exit 1
+#     fi
 
-    printf "Checking for tkinter..."
-    if python -c "import tkinter" &> /dev/null || python3 -c "import tkinter" &> /dev/null
-    then
-        echo "found"
-    else
-        echo "not found"
-        echo "tkinter not found. Please install it to continue."
-        exit 1
-    fi
+#     printf "Checking for tkinter..."
+#     if python -c "import tkinter" &> /dev/null || python3 -c "import tkinter" &> /dev/null
+#     then
+#         echo "found"
+#     else
+#         echo "not found"
+#         echo "tkinter not found. Please install it to continue."
+#         exit 1
+#     fi
 
-    printf "Checking for python-is-python3 or similar..."
-    if command -v python &> /dev/null
-    then
-        echo "found"
-    else
-        echo "not found"
-        echo "The 'python' command is not found. Please install a package like 'python-is-python3' that links the 'python' command to 'python3', or create a similar alias."
-        exit 1
-    fi
-else
-    echo "Skipping python and tkinter checks since GUI is not being built."
-fi
+#     printf "Checking for python-is-python3 or similar..."
+#     if command -v python &> /dev/null
+#     then
+#         echo "found"
+#     else
+#         echo "not found"
+#         echo "The 'python' command is not found. Please install a package like 'python-is-python3' that links the 'python' command to 'python3', or create a similar alias."
+#         exit 1
+#     fi
+# else
+#     echo "Skipping python and tkinter checks since GUI is not being built."
+# fi
 
 # Checking for realpath
-printf "Checking for realpath..."
-if command -v realpath &> /dev/null
-then
-    echo "found"
-else
-    echo "not found"
-    echo "realpath not found. Please install it to continue."
-    exit 1
-fi
+# printf "Checking for realpath..."
+# if command -v realpath &> /dev/null
+# then
+#     echo "found"
+# else
+#     echo "not found"
+#     echo "realpath not found. Please install it to continue."
+#     exit 1
+# fi
 
 # Check OS type in order to determine proper sed
 # Detect OS and set sed -i syntax
